[book]
authors = ["Karl Hallsby"]
language = "en"
multilingual = false
src = "src"
title = "Rocket-Core Documentation: The Reverse-Engineered Version"

[output.html]
default-theme = "dark"
curly-quotes = true
mathjax-support = false
copy-fonts = true
git-repository-url = "https://github.com/Constellation-FPGA/rocket-docs"
git-repository-icon = "fa-github"
